version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql # Persistent volume för SQL Server-data

  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src/MerchStore.WebApi
    volumes:
      - ./src:/src
    command: [ "dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080" ]
    ports:
      - "5293:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MerchStoreDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - ApiKey__Value=API_KEY
    depends_on:
      - sqlserver

volumes:
  sqlserver_data: # Definiera volymen
